"""Code to Zip decoded NC files."""

import logging
import traceback
from io import BytesIO
from pathlib import Path
from zipfile import ZIP_DEFLATED, ZipFile
import xml.etree.ElementTree as ET

class ZipNCFilesError(Exception):
    """Raised when there is an issue zipping the NC files."""


class ZipNCFiles:
    """Methods to zip newly decoded NC files from the Coriolis Decoder."""

    def __init__(self, wmonum: str, xml_location: str = "/mnt/data/output/xml"):
        """Initialise the instance with the wmonum."""
        self.wmonum = wmonum
        self.xml_location = xml_location

    def fetch_all_nc_paths(self) -> list[str]:
        """Parse the XML and return a list of paths generated by the decoder."""
        latest_xml_file = max(Path(self.xml_location).iterdir(), key=lambda file: file.stat().st_mtime)
        with open(latest_xml_file) as xml_file:
            root = ET.fromstring(xml_file.read())
            return [item.text for item in root.iter() if item.tag.startswith("output")]
        return []


    def zip_all_nc_files(self) -> BytesIO:
        """Zip all .nc files under the wmonum's output directory.

        Returns:
            A BytesIO object to make available for download.
        """
        try:
            buffer = BytesIO()

            with ZipFile(buffer, "w", compression=ZIP_DEFLATED) as zipfile:
                for file in self.fetch_all_nc_paths():
                    zipfile.write(file)

            buffer.seek(0)
            return buffer
        except Exception as exc:
            logging.error("An error occured during the zip file process: %s", traceback.format_exc())
            raise ZipNCFilesError from exc
