include:
  - project: dev-ops/templates/automatisation/ci-cd
    ref: feature/pipeline-generic
    file: /pipelines/generic-container-image.yml

# déploiement sur le github euroargo
container-image:github:euroargo 🐳:
  stage: container-image
  extends:
    - .container-image:docker:build-tag-push:socket
  variables:
    CONTAINER_IMAGE_REGISTRY: ghcr.io
    CONTAINER_IMAGE_NAMESPACE: euroargodev
    CONTAINER_IMAGE_NAME: coriolis-data-processing-chain-for-argo-floats-container
    CONTAINER_IMAGE_LOGIN_USER: marine-argo-coriolis-decoder-package-token-rw
    CONTAINER_IMAGE_LOGIN_TOKEN: $EUROARGODEV_PACKAGE_TOKEN
  rules:
    - !reference [ .deploy:prod:branches:rules, rules ]
    - when: never