include:
  - component: $CI_SERVER_FQDN/dev-ops/templates/automatisation/ci-cd/pipeline-generic-container-image@~latest
    inputs:
      container_image_name: "coriolis-data-processing-chain-for-argo-floats-container/ifremer"
  - component: $CI_SERVER_FQDN/dev-ops/templates/automatisation/ci-cd/pipeline-build-container-image@~latest
    inputs:
      container_image_registry: "ghcr.io"
      container_image_namespace: "euroargodev"
      container_image_name: "coriolis-data-processing-chain-for-argo-floats-container"
      container_image_login_token: "$EUROARGODEV_PACKAGE_TOKEN"
      container_image_login_user: "coriolis-data-processing-chain-package-rw"

# Pas de contrôle du formattage de la version car le decodeur argo à une convention de nommage des versions bien spécifique
.release:rules:
  rules:
    - if: '$CI_COMMIT_TAG != null'