include:
  - project: dev-ops/templates/automatisation/ci-cd
    ref: main
    file: /pipelines/generic-container-image.yml

# Pas de contrôle du formattage de la version car le decodeur argo à une convention de nommage des versions bien spécifique
.release:rules:
  rules:
    - if: '$CI_COMMIT_TAG != null'

# Déploiement du livrable docker sur la registry docker du hithub euroargo lors d'un tag
container-image:github:euroargo 🐳:
  stage: container-image
  extends:
    - .container-image:docker:build-tag-push:socket
  variables:
    CONTAINER_IMAGE_REGISTRY: ghcr.io
    CONTAINER_IMAGE_NAMESPACE: euroargodev
    CONTAINER_IMAGE_NAME: coriolis-data-processing-chain-for-argo-floats-container
    CONTAINER_IMAGE_LOGIN_USER: marine-argo-coriolis-decoder-package-token-rw
    CONTAINER_IMAGE_LOGIN_TOKEN: $EUROARGODEV_PACKAGE_TOKEN
  rules:
    - !reference [ .release:rules, rules ]
    - when: never