services:
  # Matlab runtime environment
  runtime-matlab:
    container_name: decoder-runtime-matlab
    image: ${RUNTIME_IMAGE}:${RUNTIME_IMAGE_TAG}
    volumes:
      - runtime-matlab-volume:/matlab/runtime:rw
  # Overide attributs of decode-float to match with dockerize matlab runtime
  decode-float:
    volumes:
      - runtime-matlab-volume:/mnt/runtime:ro
      - ${DECODER_DATA_INPUT_VOLUME}:/mnt/data/rsync:ro
      - ${DECODER_DATA_CONF_VOLUME}:/mnt/data/config:ro
      - ${DECODER_DATA_OUTPUT_VOLUME}:/mnt/data/output:rw
    depends_on:
      runtime-matlab:
        condition: service_started
        required: false

volumes:
  runtime-matlab-volume:
    external: false
