version: "3.9"

services:
  runtime-matlab:
    container_name: argo-runtime-matlab
    image: ${RUNTIME_IMAGE}:${RUNTIME_IMAGE_TAG}
    volumes:
      - runtime_volume:${RUNTIME_CONTAINER_PATH}:rw
  decoder-container:
    container_name: argo-decoder-container
    image: ${DECODER_IMAGE}:${DECODER_IMAGE_TAG}
    user: ${USER_ID}:${GROUP_ID}
    env_file:
      - .env
    volumes:
      - runtime_volume:/mnt/runtime:ro
      - ${DATA_INPUT}:/mnt/data/rsync:rw
      - ${DATA_CONF}:/mnt/data/config:ro
      - ${DATA_OUTPUT}:/mnt/data/output:rw
    group_add:
      - gbatch
    depends_on:
      runtime-matlab:
        condition: service_started

volumes:
  runtime_volume:
    external: false