name: CI Workflow

on:
  push:
    branches:
      # Run on our main branch
      - main
  pull_request:
    # Run for any pull requests
  release:
    types: [created]

jobs:
  python-linting:
    uses: amrit-eu/ci-cd/.github/workflows/component-python-lint.yml@main
    with:
      context: decArgo_api
  # python-security:
  #   permissions:
  #     contents: read
  #     actions: read
  #     security-events: write
  #   uses: amrit-eu/ci-cd/.github/workflows/component-python-security.yml@main
  #   with:
  #     context: decArgo_api
  container-image-build:
    # needs: [python-linting, python-security]
    needs: [python-linting]
    uses: amrit-eu/ci-cd/.github/workflows/component-container-image.yml@main
    with:
      context: decArgo_api
      image-path: ghcr.io/amrit-eu/coriolis-data-processing-chain-for-argo-floats-container/api
  container-image-security:
    needs: [container-image-build]
    permissions:
      contents: read
      actions: read
      security-events: write
    uses: amrit-eu/ci-cd/.github/workflows/component-container-image-security.yml@main
    with:
      image-path: ghcr.io/amrit-eu/coriolis-data-processing-chain-for-argo-floats-container/api

